;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        cycle-spacing
        electric-newline-and-maybe-indent
        indent-for-tab-command
        markdown-beginning-of-line
        markdown-cycle
        markdown-end-of-line
        markdown-outdent-or-delete
        move-dup-move-lines-up
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        phi-search
        eval-print-last-sexp
        revert-buffer
        wdired-finish-edit
        wgrep-finish-edit
        ))
