;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cycle-spacing
        electric-newline-and-maybe-indent
        markdown-cycle
        ))

(setq mc/cmds-to-run-once
      '(
        eval-print-last-sexp
        wgrep-finish-edit
        ))
