;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        cycle-spacing
        dabbrev-expand
        downcase-region
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        end-of-buffer
        indent-for-tab-command
        markdown-beginning-of-line
        markdown-cycle
        markdown-end-of-line
        markdown-outdent-or-delete
        move-dup-duplicate-down
        move-dup-move-lines-down
        move-dup-move-lines-up
        org-self-insert-command
        upcase-region
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        embark-act
        eval-print-last-sexp
        handle-switch-frame
        kmacro-end-or-call-macro
        phi-search
        project-find-file
        revert-buffer
        switch-window-then-delete
        symbol-overlay-jump-next
        wdired-finish-edit
        wgrep-abort-changes
        wgrep-finish-edit
        winner-undo
        ))
